// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB46O1BrE9SJfcpWAB5BPaoDEPSammCUVQ',
    appId: '1:280226773868:web:b9cb0306e823214cc81149',
    messagingSenderId: '280226773868',
    projectId: 'app-libros-85777',
    authDomain: 'app-libros-85777.firebaseapp.com',
    storageBucket: 'app-libros-85777.appspot.com',
    measurementId: 'G-WN2JKM3BHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDshiVgzSz3isiOu7drQqHTe_OsL25PfS4',
    appId: '1:280226773868:android:b13154c215f24caec81149',
    messagingSenderId: '280226773868',
    projectId: 'app-libros-85777',
    storageBucket: 'app-libros-85777.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlIyUcNDUC40MFNbrUsFRS3kQyy24HSKI',
    appId: '1:280226773868:ios:bf8bcf168b718a4ac81149',
    messagingSenderId: '280226773868',
    projectId: 'app-libros-85777',
    storageBucket: 'app-libros-85777.appspot.com',
    iosClientId: '280226773868-frpilmlh26gk5kgo9do5iu1uuanieqce.apps.googleusercontent.com',
    iosBundleId: 'com.example.misLibros',
  );
}
